1.0 fdo profile
DiSSCo/openDS pull request #138
Opened 2024-09-03 10:58 UTC by southeo

Introduced 1.0.0 Version of FDO Profiles according to finalization discussion

** Handle Objects**
- Handle-kernel
- Annotation
- Data-mapping
- Machine-annotation-service
- Source-system

**DOI Objects**
- Doi-kernel
- Digital-specimen
- Digital-media

2024-09-17 07:57 UTC, TomDijkema approved these changes
:deer

2024-09-24 11:52 UTC, sharifX requested changes

2024-09-24 11:52 UTC, sharifX commented on data-model/fdo-profile/digital-media/1.0.0/schema/digital-media-request-attributes.json
> +      "description": "ROR or, in absence of a ROR, Wikidata Qnumber for the administrative organisation responsible for hosting the digital media object. Note that this can be DiSSCo also (use DiSSCo
typo fix. "note the.."

2024-09-24 14:46 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation-request.json
I would add a targetTypeName with the name of the targetType (in this case DigitalSpecimen) to follow the policy to use an identifier in combination with a name where possible.

2024-09-24 14:49 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation-request.json
same for type, I would add typeName

2024-09-24 14:51 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation-request.json
is a MD5 hash resistant enough to collisions?

2024-09-24 14:53 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation.json
add VIEW=JSON to 10320/loc for consistency (although we do not currently have a HTML view for the annotation)

2024-09-24 15:38 UTC, wouteraddink requested changes

2024-09-24 15:38 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/schema/annotation.json
update idx6 example with 10.3535 prefix, add VIEW=JSON to10320/loc

2024-09-24 15:38 UTC, wouteraddink commented on data-model/fdo-profile/data-mapping/1.0.0/schema/data-mapping.json
I am missing issuedForAgent and issuedForAgentName

2024-09-24 15:38 UTC, wouteraddink commented on data-model/fdo-profile/digital-specimen/1.0.0/schema/digital-specimen-request-attributes.json
typo in topicCategory, should be Microfungi not Mircofungi

2024-09-24 15:38 UTC, wouteraddink commented on data-model/fdo-profile/digital-specimen/1.0.0/schema/digital-specimen-request-attributes.json
for topicDiscipline we need to add Archeology at some point (can leave it out now since not supported yet in DiSSCover)

2024-09-25 09:19 UTC, southeo commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation-request.json
MD5 is definitely resistant enough to random collisions. 
- There's a 1/(2^128) chance of any 2 random messages colliding. 
- If we have 2^64 messages, there is a 50% chance of there being at least one collision (see [birthday problem](https://en.wikipedia.org/wiki/Birthday_problem))
     - That's 1.8x10^19 annotations to get to that point. If we're at that many annotations, we have a few other technical issues to address first!

2024-09-25 09:32 UTC, southeo commented on data-model/fdo-profile/data-mapping/1.0.0/schema/data-mapping.json
these terms were moved to only refer to the DOI profiles only

2024-09-30 10:05 UTC, sharifX approved these changes
looks good. a small comment.

2024-10-01 07:35 UTC, wouteraddink requested changes
Almost there! a few requests for changes still, see comments

2024-10-01 07:35 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation.json
it is now implemented as ID=JSON but the ID should not change, a VIEW parameter should be added. ID attributes are given an integer in the Handle documentation, I am not sure that is actually required but people using Handles may expect an integer there so I would keep the ID integers. They may be handy if there are for example multiple URLS with VIEW=JSON, to display one of them with preference using a weight (e.g. one is served in Chine, the other in Europe and for traffic coming from Europe you may prefer the one served from a location in Europe).

2024-10-01 07:35 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation.json
now pidIssuerName is changed to the ROR, but the ROR should be in pidIssuer and pidIssuerName should be DiSSCo

2024-10-01 07:35 UTC, wouteraddink commented on data-model/fdo-profile/digital-media/1.0.0/schema/digital-media-request-attributes.json
dcterms:license was changed to licenseName, but filled in the example with a URL pointing to the license, for example https://spdx.org/licenses/CC0-1.0.json.  Following our policy to include both a name and an identifier, it may be best to have both a term 'licenseURL' for e.g. "https://spdx.org/licenses/CC0-1.0.json" and a term 'licenceName' for e.g. "Creative Commons Zero v1.0 Universal". In SPDX the licenseID is "CC0-1.0" but since we use the URL as the ID I think we do not need to include that.

2024-10-01 07:35 UTC, wouteraddink commented on data-model/fdo-profile/digital-media/1.0.0/schema/digital-media.json
In the description you can remove "(use DiSSCo QID in that case)" since DiSSCo now has a ROR

2024-10-02 13:22 UTC, southeo commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation.json
Hi Wouter,

Do you have additional documentation on how to implement this? based on the [handle.net documentation](https://www.handle.net/overviews/handle_type_10320_loc.html), there are the following selection methods defined for the 10320/loc field:
- locatt, which allows a client to select a location based on id (e.g. `20.5555/1234?locatt=id:0`)
- weight
- country

Nothing about selecting based on a views

Fortunately, there's nowhere in the documentation I could find that indicates the id must be an integer, so I implemented the proposed functionality using id instead. User-provided locations are given an integer identifier.

2024-10-02 13:36 UTC, southeo commented on data-model/fdo-profile/digital-media/1.0.0/schema/digital-media-request-attributes.json
Exactly. The changes you describe were made in the digital media fdo profile (digital-media.json), but this is the schema for the fdo request made to the handle API. In the processing service, we're trying to map an open string field dcterms:license to these 2 fields. the handle API looks at the license coming in from the processing service, and determines the license it's resolvable or not.  

if it's resolvable, the handle api populates licenseUrl and licenseName with the resolved name. If it's not resolvable, the handle api populates just "licenseName". 

This structure exists based on the assumption that a client can't determine whether the license is resolvable or not. However, it's possible down the road some client has more structured data. for that reason, I'm adding 3 license terms: license (for when you don't know what license you have), and licenseUrl and licenseName for when you can distinguish between the two.

2024-10-02 13:49 UTC, southeo commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation.json
I'm not 100% sure if the handle system supports that. In [their documentation](https://www.handle.net/overviews/handle_type_10320_loc.html), they say: 

> The currently defined selection methods are:
> - Locatt (select by id)
> -  country
> - weight

However, they also say: 

> The attributes for the set of locations, as well as each location entry in the set, are open-ended to allow for future capabilities.

So it might support it, it might not. Will need to test. If it fails, using the id this way should work. There's nothing in the documentation that says that the id needs to be an integer.

2024-10-04 11:45 UTC, wouteraddink commented on data-model/fdo-profile/annotation/1.0.0/examples/example-annotation.json
ok, how I read the documentation you should be able to add any attribute you like. If it does not work then please use the id instead but having both attributes would be more flexible.

2024-10-04 12:00 UTC, wouteraddink approved these changes

2024-10-07 12:22 UTC, merged