Feature/opends 0.4.0
DiSSCo/openDS pull request #201
Opened 2024-10-02 15:01 UTC by samleeflang

**TO DO add all github tickets connected to this PR**

2024-10-07 12:06 UTC, sharifX requested changes

2024-10-07 12:06 UTC, sharifX commented on data-model/fdo-type/tettris-service/0.1.0/schema/example-tom-impl.json
empty file?

2024-10-07 13:04 UTC, samleeflang commented on data-model/fdo-type/tettris-service/0.1.0/schema/example-tom-impl.json
:upside_down_face: made an example for Tom which seems to have gotten in the PR. Removing it.

2024-10-07 13:04 UTC, samleeflang commented on data-model/fdo-type/annotation/0.4.0/examples/approved-annotation-example.json
> +    "ods:tombstoneText": "This object was made by mistake",
Ok, this is a free text field so we have no control over what is in there.
Did notice that it used an old tombstone schema, fixed that

2024-10-07 14:36 UTC, sharifX approved these changes

2024-10-07 15:50 UTC, wouteraddink requested changes
See comments. This is a very big PR (even though I did not review the examples) and I could not view the changes with diff so I hope I did not miss things. Only few comments, so well done! My comments are mainly for the identifier part that may need some further discussion.

2024-10-07 16:48 UTC, wouteraddink commented
one more thing: with ISO 639-2 it would be better to use the terminological codes, so ISO 639-2/T and not  ISO 639-2/B (bibliographic) variant in cases where there is a variant, which is mainly there for legacy bibliographic catalog purposes. So the code for Dutch should be "nld" not "dut" for example. The first one is  ISO 639-2/T  and the second one is ISO 639-2/B.

2024-10-08 06:43 UTC, samleeflang commented on data-model/fdo-type/data-mapping/0.4.0/schema/data-mapping.json
I will change the text enum to reflect the official casing. 
With regards to the use of a URL or PID for controlled vocabularies I would agree.
However, to my knowledge there is no existing controlled vocab for this (or did I miss it?) and we don't have a vocab server where we can create URL/PID for the controlled vocabs.
The same issue is for all the controlled vocabs we use, for example `ods:status` or `ods:topicDiscipline`.
When the vocab server is there we also need to consider if we want human-readable format and machine-readable format.
I have seen several approaches for this, the [`dwciri`](http://rs.tdwg.org/dwc/iri/lifeStage), but also terms with the suffix [`Literal` ](http://rs.tdwg.org/ac/terms/subjectPartLiteral). Do we then also want [`xxxVocabulary`](http://rs.tdwg.org/ac/terms/subjectCategoryVocabulary) terms to indicate which vocab we use or not?

2024-10-08 06:49 UTC, samleeflang commented on data-model/fdo-type/shared-model/0.4.0/schema/tombstone-metadata.json
Note that these are examples and this is not an enumeration. I would rather have it as an enumeration, and I believe Sou got a comprehensive list. We would need to check the list and then preferable create the controlled vocabulary (when we got the vocab server). I will add this as an additional example

2024-10-08 06:52 UTC, samleeflang commented on data-model/fdo-type/digital-media/0.4.0/schema/digital-media.json
Added MNHN to examples

2024-10-08 07:02 UTC, samleeflang commented on data-model/fdo-type/digital-specimen/0.4.0/schema/taxon-identification.json
Adding two example from our actual data, so specimen in the test env that have been mapped to COL.

2024-10-08 07:11 UTC, samleeflang commented
> one more thing: with ISO 639-2 it would be better to use the terminological codes, so ISO 639-2/T and not ISO 639-2/B (bibliographic) variant in cases where there is a variant, which is mainly there for legacy bibliographic catalog purposes. So the code for Dutch should be "nld" not "dut" for example. The first one is ISO 639-2/T and the second one is ISO 639-2/B.

I tried to keep in line with Audoban Core with this, which just accepts any ISO 639-2 standard and points to a controlled vocab which puts Dutch -> `dut`. We could deviate, but I am unsure if we can then still use `ac:metadataLanguage` and `ac:metadataLanguageLiteral`.  We could also scrap the metadataLanguages as we already has a discussion about it usefullness. We would then keep only `dcterms:language` which we could limit to ISO 639-2/T.

2024-10-08 08:00 UTC, wouteraddink commented on data-model/fdo-type/data-mapping/0.4.0/schema/data-mapping.json
I was thinking of including the urls for the standards: https://dwc.tdwg.org/, https://abcd.tdwg.org/xml/documentation/primer/2.06/, https://github.com/tdwg/efg

indeed we have no vocab server yet so we cannot create pids for them currently. if we have them I think we need to include both the human-readable name and machine readable pid.

2024-10-08 11:12 UTC, samleeflang commented on data-model/fdo-type/data-mapping/0.4.0/schema/data-mapping.json
hmm, let's stick with the string for now. I don't think the URL really adds anything. It isn't a controlled vocab of the data standard, these are just links to resources about them. We use the string to check which type of translator we deploy, that would also get more complicated.

2024-10-08 11:40 UTC, samleeflang commented on data-model/fdo-type/shared-model/0.4.0/schema/identifier.json
Ok these are a couple of tickets bundled into one:
- Some confusion about title and type. I followed your suggestion and took over the enum from DataCite for type. It will not always be clear what type an identifier is 
- Additional spot for MachineReadableMetadataURL. I am not sure if that needs to go in here or in `ods:EntityRelationship`. In the ER we indicate links to resource where a human/machine can go for additional info. For both however I don't know if this is necessary right now. If we need it now I would be in favour of an implementation agnostic term (not with JSON in it)
- I do not agree with changing the examples. The subject can be seen as additional keywords for the identifier. The `dwc:catalogueNumber` is however the TDWG way to indicate a catalogueNumber which to me should therefore be the title. That a local institution calls it Registratie nummer internally is for me a keyword. 
- Ok yes that should good, I am not sure about the name though, with `ods:GupriLevel` you need to know what Gupri means before you know what the term means. In addition to the term it is often difficult to know only from the identifier what level it is, how do we know if the identifier is persistent? I already had that issue earlier with the `ods:isPersistent` term.
- Ok we could make space for that, we might not always know the status but at elast the term is there

2024-10-08 12:02 UTC, samleeflang commented on data-model/fdo-type/shared-model/0.4.0/schema/identifier.json
- `dcterms:title` en `dcterms:identifier` will be required

2024-10-08 12:04 UTC, samleeflang commented on data-model/fdo-type/shared-model/0.4.0/schema/identifier.json
Pushed the changes for the `odsIdentifier` object. When they are accepted I will update all examples accordingly

2024-10-09 12:38 UTC, wouteraddink approved these changes

2024-10-09 13:03 UTC, merged